experiment_name: extract_evm_bert_chunk_features_mean
hf_model_path: checkpoints/pretrain_evm_bert_base_full_bjut/hf_model
vocab_path: data/processed/BJUT_SC01/evm_vocab.json
data_dir: data/processed/BJUT_SC01

train_path: data/processed/BJUT_SC01/train_mlsmote.jsonl
valid_path: data/processed/BJUT_SC01/valid.jsonl
test_path: data/processed/BJUT_SC01/test.jsonl

output_dir: data/features/evm_bert_chunks_mean
report_dir: data/reports
log_dir: logs

max_len: 512
chunk_content_size: 510
chunk_stride: 510
max_chunks_per_contract: 16

batch_size: 64
num_workers: 4
fp16: true

pooling: masked_mean
is_transductive_pretraining: true

